---
title: "Nathan Haferman"
---

Hi, my name is Nathan Haferman. Currently, I am a Junior at Appalachian State University and am majoring in Marketing with a minor in statistics. I was born in Columbus Ohio, and moved to Winston Salem NC when in 2006 due to a change in my fathers job. It was by far the best move of our lives. I grew up doing any kind of physical activity I could find. Soccer was my number one thing to do. I loved it and played till my senior year. Additionally, I was on the swim team and the tennis team which were some of my favorite moments of my life. Additionally, during this time, I thoroughly enjoyed hiking and backpacking. This helped lead me to choosing App as the college that I wanted to go to.

Entering Appalachian, I was very nervous of the new environment. Thankfully, with friendly people and lots to do, it was a very easy transition. I quickly jumped into the year and helped start two clubs. One of them being the ASPCL which stood for the Appalachian Society for Professional Collegiate Leaders. Unfortunately, due to lack of leadership, the club dropped. Even though it was a failure, I learned lots. Additionally, I got involved in lots of intramural sports such as volleyball, soccer, and dodgeball. 

Fast forward to now and I am in my junior year. I have been working at the Appalachian Bookstore for a year and a half now where I sell computers an computer accessories. I am still heavily involved in intramural sports. I am definitely looking forwar to graduation but am still enjoying every day I spend at Appalachian State University!

One of my favorite things to do is traveling with my family. Each year we always try to go on a vacation and most of the time it is usually to the mountains. I have been blessed with a family that loves to backpack and hike with me. One of my favorite trips has been to Banff in Canada. I have never before seen a beauty quite like this. The mountains were huge and the waters were blue. I am still itching to get out there again. Additionally, I have taken a road trip out west with my siblings. On this trip we hit many inspiring national parks like: Grand Teton, Glacier, Yellowstone, Olympia, and The Cascades. This was by far the time of my life.





